export const environment = {
  production: false,
  openAiKey: "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",
  tmdbAccessKey:"eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NDQzOGRiMjk1OWQyY2JjYTA3MmNhOTFiY2YyOTZmZSIsInN1YiI6IjY0YzhkNjc0Zjc5NGFkMDEzOTU5Y2U2NiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.wuWKQKY1qoq4zWAnXa7rYk15KxY12ctcsBbivwEvlx4"
};
